name = "zipper-example"
defaultTargets = ["Zippers"]

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "no-modules/847084e80500726e4331dded5f17007ddaf89c31"

[[lean_lib]]
name = "Zippers"
