name = "zipper-example"
defaultTargets = ["Zippers"]

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "no-modules/d047cb484b2f3598187450935dbcc84d078cb581"

[[lean_lib]]
name = "Zippers"
