name = "zipper-example"
defaultTargets = ["Zippers"]

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "no-modules/3a75ede05278806fd3249bb0c97a6fb5777a4f7d"

[[lean_lib]]
name = "Zippers"
